<a href="https://colab.research.google.com/github/Ananyaramamoolya/edaexample/blob/main/data_cleaning_dirty_employee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [294]:
import pandas as pd
import numpy as np

In [295]:
df=pd.read_csv("dirty-employee.csv")

In [296]:
print(df.head())

   Employee_ID     Full_Name    Age  Gender Joining_Date  \
0          101   Akif Attar    25.0       M     12-02-26
1          102      Ali Khan   30.0    Male    20-Mar-25
2          103   Sara Sheikh    NaN  Female     12-05-20
3          104   Ahmed Patel   -5.0    male    15-Jan-24
4          105   Fatima Noor  180.0       F     10-08-23

               Department   Salary      Country           Phone Marks  \
0                      IT  ?25,000        India      9876543210    85
1  Information Technology  ?30,000  -9876543120      9876543211    90
2                    I.T.  ?28,500        INDIA    (987)6543212    88
3                      HR  ?35,000          ind    987-654-3213    92
4                 Finance  ?40,000       Bharat  +91 9876543214    95

   Unnamed: 10
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN

In [297]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   20 non-null     int64
 1   Full_Name     19 non-null     object
 2   Age           17 non-null     float64
 3   Gender        20 non-null     object
 4   Joining_Date  18 non-null     object
 5   Department    20 non-null     object
 6   Salary        20 non-null     object
 7   Country       20 non-null     object
 8   Phone         19 non-null     object
 9   Marks         19 non-null     object
 10  Unnamed: 10   1 non-null      float64
dtypes: float64(2), int64(1), object(8)
memory usage: 1.8+ KB
None

In [298]:
df=df.drop_duplicates()

In [299]:
df.isnull().sum()

Employee_ID      0
Full_Name        1
Age              3
Gender           0
Joining_Date     2
Department       0
Salary           0
Country          0
Phone            1
Marks            1
Unnamed: 10     19
dtype: int64

In [300]:
df['Full_Name']=df['Full_Name'].fillna("").astype(str).str.strip().str.title()

In [301]:
df["Age"]=df["Age"].fillna(0)
df_Filtered=df[(df["Age"]>=1)&(df["Age"]<=100)]

In [302]:
df["Joining_Date"]=pd.to_datetime(df["Joining_Date"],errors="coerce")
df["Joining_Date"]=df["Joining_Date"].dt.strftime("%Y-%m-%d")

/tmp/ipykernel_3159/3985467861.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Joining_Date"]=pd.to_datetime(df["Joining_Date"],errors="coerce")

In [303]:
df["Phone"]=df["Phone"].astype(str).str.replace(r"[^0-9]","",regex=True)

In [304]:
df["Marks"]=pd.to_numeric(df["Marks"],errors="coerce")
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())

In [305]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [306]:
df.to_csv("Cleaned_employee_data.csv",index=False)

In [307]:
df.isnull().sum()

Employee_ID     0
Full_Name       0
Age             0
Gender          0
Joining_Date    3
Department      0
Salary          0
Country         0
Phone           0
Marks           0
dtype: int64

In [308]:
df["Joining_Date"]

0     2026-12-02
1     2025-03-20
2     2020-12-05
3     2024-01-15
4     2023-10-08
5            NaN
6     2022-12-31
7     2024-06-15
8     2023-06-10
9     2025-01-11
10    2025-03-20
11    2021-03-14
12    2022-08-07
13           NaN
14    2021-11-30
15    2020-09-15
16    2023-08-15
17    2022-08-20
18    2024-10-01
19           NaN
Name: Joining_Date, dtype: object

In [309]:
df["Joining_Date"].fillna("2024-01-01",inplace=True)

In [310]:
df.isnull().sum()

Employee_ID     0
Full_Name       0
Age             0
Gender          0
Joining_Date    0
Department      0
Salary          0
Country         0
Phone           0
Marks           0
dtype: int64